### ISSUE TITLE
rebase interattivo

### ISSUE THREAD

**Issue by FabioZTessitore** [luca998/helloworld#1]
devi imparare a fare il rebase interattivo

**Comment by luca998** [comment]
ok da dove devo partire?

**Comment by FabioZTessitore** [comment]
prima cosa: capire la situazione della nostra repository

prova a dare il comando
```bash
$ git log --oneline --graph --decorate --all
```
e vedi se ti trovi con me
![schermata da 2016-01-28 21-09-28](https://cloud.githubusercontent.com/assets/3002194/12657428/8cd81494-c603-11e5-9b91-a3b823198944.png)

ps.
*. --oneline permette di stampare un commit per riga
*. --graph disegna un grafo con caratteri (puoi vedere che c'è una diramazione ad un certo punto)
*. --all mostra tutte le branch (quando ce ne saranno varie)
*. --decorate mostra i nomi delle branch e la posizione del cursore HEAD

**Comment by luca998** [comment]
Si mi trovo con voi

**Comment by FabioZTessitore** [comment]
l'idea è questa:

stai collaborando su un progetto con altre persone. Ti era stato chiesto di implementare la funzionalità "hello world" e tu l'hai fatta.
Però nel lavorare hai creato una serie di commit inutili. Per una cosa come "hello world" ne bastavano un paio, quello iniziale e quello finale.

Puoi allora prendere il commit b794b46 (l'ultimo in ordine di tempo) e "ribasarlo" (cambiargli la base) facendolo derivare direttamente dal commit iniziale 3a1e39e

Per fare questo però bisogna vedere che fine devono fare tutti i commit intermedi

Fin qui ci sei?

**Comment by luca998** [comment]
si

**Comment by FabioZTessitore** [comment]
ok. per prima cosa assicurati di essere sul commit di cui vuoi fare il rebase. Siccome è l'ultimo è indicato anche con master. In ogni caso puoi fare `git checkout master'

A questo punto chiedi di fare il rebase interattivo (mi raccomando, interattivo perché devi decidere tu cosa fare dei commit intermedi, attenzione al parametro -i)
`git rebase -i 3a1e39e`

Si aprirà un editor di testi così:
![schermata da 2016-01-28 22-11-37](https://cloud.githubusercontent.com/assets/3002194/12658918/23efbf82-c60c-11e5-8c63-a0ea42cbff68.png)

Nota la lista dei commit (in questo caso il più vecchio sta su e il più recente giù, ma al momento non importa).
Vicino ad ogni commit c'è la parola pick che come puoi leggere più in basso significa "usa il commit"

Quello che devi fare è sostituire la parola pick con squash così come vedi (il primo deve rimanere pick per forza)
![schermata da 2016-01-28 22-15-43](https://cloud.githubusercontent.com/assets/3002194/12659020/be98ee50-c60c-11e5-8bce-238ac286c870.png)

A questo punto salva ed esci. Se tutto va bene ti darà errore.
Fammi sapere

**Comment by luca998** [comment]
mi dice questo quando do il comando git rebase -i "Cannot rebase: You have
unstaged changes.
Please commit or stash them."


Il giorno 28 gennaio 2016 22:16, Fabio Z Tessitore <notifications@github.com

**Comment by FabioZTessitore** [comment]
Evidentemente hai fatto delle modifiche ai file (anche involontariamente)

Puoi cancellare la directory e rifare il clone per ricominciare daccapo oppure fai un `git status` per vedere qual è la situazione, `git add .` per fare stage delle modifiche e `git commit` per chiudere

**Comment by luca998** [comment]
Ok ho risolto, ora mi da errore come previsto

**Comment by FabioZTessitore** [comment]
ok, ricordi come procedere?

2016-01-29 19:31 GMT+01:00 luca998 <notifications@github.com>:

**Comment by luca998** [comment]
non ricordo bene i comandi

**Comment by FabioZTessitore** [comment]
Rifai git status

Ti dirà che c'è un file da cancellare

Git rm nomefile

Git status ora ti dirà che ha capito la modifica

Git rebase --continue

Il venerdì 29 gennaio 2016, luca998 <notifications@github.com> ha scritto:

**Comment by luca998** [comment]
Ok mi trovo

**Comment by FabioZTessitore** [comment]
Ok push forzato così più tardi controllo

Il venerdì 29 gennaio 2016, luca998 <notifications@github.com> ha scritto:

**Comment by luca998** [comment]
va bene

**Comment by FabioZTessitore** [comment]
ok, puoi cancellare questa repo
