### ISSUE TITLE
Doppio

### ISSUE THREAD

**Issue by FabioZTessitore** [luca998/helloworld#5]
Creare un programma doppio.py che chiede all'utente
di inserire un numero intero e quindi stampa
il doppio del numero inserito.

**Comment by luca998** [comment]
si poteva fare anche num*2

**Comment by FabioZTessitore** [comment]
Dici la verità, ti sei messo a fare delle modifiche direttamente dal sito ...

Lo puoi anche fare quando sono cose banali, ma ricorda di fare il pull prima di fare altre modifiche in locale sennò finisce come ora che sei costretto a fare merge.

Tutto chiaro?

**Comment by luca998** [comment]
chiarissimo
